<?php
/**
 * Img on left and content on right
 */
return array(
	'title'      => __( 'Img on left and content on right', 'drchrono' ),
	'categories' => array( 'sections' ),
	'content'    => '<!-- wp:greenshift-blocks/container {"id":"gsbp-d1dc351e-0d7e","calcOperator":["-","-","-","-"],"secondWidth":[null,null,null,null],"secondWidthUnit":["px","px","px","px"],"width":[null,null,null,null],"widthUnit":["%","%","%","%"],"minHeight":[null,null,null,null],"rowspan":[],"columnspan":[],"order":[],"minHeightUnit":["px","px","px","px"],"flexbox":{},"animation":{"duration":700,"easing":"ease","type":""},"background":{},"overlay":{},"border":{"borderRadius":{"values":{},"unit":"px","locked":true}},"spacing":{"margin":{"values":{"top":["40"],"bottom":["40"]},"unit":["px","px","px","px"],"locked":false},"padding":{"values":{},"unit":["px","px","px","px"],"locked":false}},"shadow":{},"typography":{},"position":{"positionType":["","","",""],"positions":{"values":{}}},"shapeDivider":{"topShape":{},"bottomShape":{}},"responsive":{},"csstransform":{},"carousel":{"arrowPos":[null,null,null,null],"arrowSize":[null,null,null,null],"arrowPosV":[null,null,null,null]},"imageBorder":{"borderRadius":{"values":{},"unit":"px","locked":true}},"imageShadow":{},"align":"wide"} -->
    <div id="gspb_container-id-gsbp-d1dc351e-0d7e" class="gspb_container gspb_container-gsbp-d1dc351e-0d7e wp-block-greenshift-blocks-container alignwide"><!-- wp:greenshift-blocks/row {"id":"gsbp-6d6547f4-edbd","gutterClassName":"gspb_row\u002d\u002dgutter-20","rowLayout":"2","columnPosition":"center","displayStyles":false} -->
    <div id="gspb_row-id-gsbp-6d6547f4-edbd" class="gspb_row gspb_row-id-gsbp-6d6547f4-edbd wp-block-greenshift-blocks-row gspb_row--gutter-20"><div class="gspb_row__content"> <!-- wp:greenshift-blocks/row-column {"id":"gsbp-f28a85e0-52b1","width":[45,null,null,null],"gutterclass":"gspb_row\u002d\u002dgutter-20","columnSize":"6"} -->
    <div id="gspb_col-id-gsbp-f28a85e0-52b1" class="gspb_row__col--6 wp-block-greenshift-blocks-row-column gspb_col-id-gsbp-f28a85e0-52b1"><!-- wp:greenshift-blocks/image {"id":"gsbp-65aba0ac-5b51","align":["left",null,null,null],"valign":["middle",null,null,null],"width":["auto",null,null,null],"originalWidth":640,"originalHeight":368,"mediaurl":"http://drchrono.local/wp-content/uploads/2022/10/api-devices.png","mediaid":176,"alt":"","lightbox":true} -->
    <div id="gspb_image-id-gsbp-65aba0ac-5b51" class="gspb_image gspb_image-id-gsbp-65aba0ac-5b51 gssimglightbox wp-block-greenshift-blocks-image"><img src="http://drchrono.local/wp-content/uploads/2022/10/api-devices.png" data-src="" alt="" width="640" height="368"/></div>
    <!-- /wp:greenshift-blocks/image --></div>
    <!-- /wp:greenshift-blocks/row-column -->
    
    <!-- wp:greenshift-blocks/row-column {"id":"gsbp-73dc491a-f8dd","width":[55,null,null,null],"gutterclass":"gspb_row\u002d\u002dgutter-20","columnSize":"6"} -->
    <div id="gspb_col-id-gsbp-73dc491a-f8dd" class="gspb_row__col--6 wp-block-greenshift-blocks-row-column gspb_col-id-gsbp-73dc491a-f8dd"><!-- wp:greenshift-blocks/heading {"id":"gsbp-ece12837-c5b4","headingContent":"Conduct Video Visits Without Additional Integrations","typography":{"textShadow":{},"color":"#333333","usePreset":true,"preset":"one","alignment":["left"],"customweight":"bold"}} -->
    <h2 id="gspb_heading-id-gsbp-ece12837-c5b4" class="gspb_heading gspb_heading-id-gsbp-ece12837-c5b4 ">Conduct Video Visits Without Additional Integrations</h2>
    <!-- /wp:greenshift-blocks/heading -->
    
    <!-- wp:greenshift-blocks/iconlist {"id":"gsbp-911be20d-e3db","iconsList":[{"icon":{"icon":{"font":"rhicon rhi-circle-solid","svg":"","image":""},"fill":"#333333","fillhover":"","iconSize":[8,null,null,null],"rotateY":false,"rotateX":false,"type":"font"},"content":"Schedule a new Video Visit or convert an existing appointment directly from your EHR."},{"icon":{"icon":{"font":"rhicon rhi-circle-solid","svg":"","image":""},"fill":"#333333","fillhover":"","iconSize":[8,null,null,null],"rotateY":false,"rotateX":false,"type":"font"},"content":"Let patients schedule their own in-person or video visits from their patient portal."},{"icon":{"icon":{"font":"rhicon rhi-circle-solid","svg":"","image":""},"fill":"#333333","fillhover":"","iconSize":[8,null,null,null],"rotateY":false,"rotateX":false,"type":"font"},"content":"Conduct Video Visits without additional downloads or software required on either the provider or patient side."},{"icon":{"icon":{"font":"rhicon rhi-circle-solid","svg":"","image":""},"fill":"#333333","fillhover":"","iconSize":[8,null,null,null],"rotateY":false,"rotateX":false,"type":"font"},"content":"Send automated patient emails such as appointment confirmations and reminders."}],"direction":"flex-start","vDirection":"center","colorGlobal":"#333333","sizeGlobal":8,"currentItem":"0","background":{},"blockBackground":{},"border":{"borderRadius":{"values":{},"unit":"px","locked":true}},"blockBorder":{"borderRadius":{"values":{},"unit":"px","locked":true}},"spacing":{"margin":{"values":{"top":["20"]},"unit":["px","px","px","px"],"locked":false},"padding":{"values":{},"unit":["px","px","px","px"],"locked":false}},"spacingList":{"margin":{"values":{},"unit":["px","px","px","px"],"locked":false},"padding":{"values":{},"unit":["px","px","px","px"],"locked":false}},"typography":{"textShadow":{},"color":"#333333","usePreset":true,"preset":"four"},"shadow":{},"blockShadow":{},"icon_spacing":{"margin":{"values":{},"unit":["px","px","px","px"],"locked":false},"padding":{"values":{},"unit":["px","px","px","px"],"locked":false}},"blockWidth":{"customWidth":{"value":[],"unit":["px","px","px","px"]},"customHeight":{"value":[],"unit":["px","px","px","px"]}},"animation":{"duration":700,"easing":"ease","type":""},"responsive":{},"position":{"positionType":["","","",""],"positions":{"values":{}}},"csstransform":{}} -->
    <div id="gspb_iconsList-id-gsbp-911be20d-e3db" class="gspb_iconsList gspb_iconsList-id-gsbp-911be20d-e3db wp-block-greenshift-blocks-iconlist"><div class="gspb_iconsList__item" data-id="0"><svg class="" style="display:inline-block;vertical-align:middle" width="18" height="18" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg"><path style="fill:#565D66" d="M512 16c-274 0-496 222-496 496s222 496 496 496 496-222 496-496-222-496-496-496z"></path></svg><span class="gspb_iconsList__item__text">Schedule a new Video Visit or convert an existing appointment directly from your EHR.</span></div><div class="gspb_iconsList__item" data-id="1"><svg class="" style="display:inline-block;vertical-align:middle" width="18" height="18" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg"><path style="fill:#565D66" d="M512 16c-274 0-496 222-496 496s222 496 496 496 496-222 496-496-222-496-496-496z"></path></svg><span class="gspb_iconsList__item__text">Let patients schedule their own in-person or video visits from their patient portal.</span></div><div class="gspb_iconsList__item" data-id="2"><svg class="" style="display:inline-block;vertical-align:middle" width="18" height="18" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg"><path style="fill:#565D66" d="M512 16c-274 0-496 222-496 496s222 496 496 496 496-222 496-496-222-496-496-496z"></path></svg><span class="gspb_iconsList__item__text">Conduct Video Visits without additional downloads or software required on either the provider or patient side.</span></div><div class="gspb_iconsList__item" data-id="3"><svg class="" style="display:inline-block;vertical-align:middle" width="18" height="18" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg"><path style="fill:#565D66" d="M512 16c-274 0-496 222-496 496s222 496 496 496 496-222 496-496-222-496-496-496z"></path></svg><span class="gspb_iconsList__item__text">Send automated patient emails such as appointment confirmations and reminders.</span></div></div>
    <!-- /wp:greenshift-blocks/iconlist -->
    
    <!-- wp:greenshift-blocks/button {"id":"gsbp-f5b4d4e6-b10d","buttonContent":"Schedule A Demo","background":{"color":"#3C86FD","overlayOpacity":100},"backgroundCook":{},"panelBackground":{},"overlay":{},"spacing":{"margin":{"values":{"top":["20"]},"unit":["px","px","px","px"],"locked":false},"padding":{"values":{},"unit":["px","px","px","px"],"locked":false}},"panelSpacing":{"margin":{"values":{},"unit":["px","px","px","px"],"locked":false},"padding":{"values":{},"unit":["px","px","px","px"],"locked":false}},"iconSpacing":{"margin":{"values":{},"unit":["px","px","px","px"],"locked":false},"padding":{"values":{},"unit":["px","px","px","px"],"locked":false}},"border":{"borderRadius":{"values":{"topLeft":"6","topRight":"6","bottomRight":"6","bottomLeft":"6"},"unit":"px","locked":true},"style":{},"size":{},"color":{},"styleHover":{},"sizeHover":{},"colorHover":{}},"borderCook":{"borderRadius":{"values":{},"unit":"px","locked":true}},"panelBorder":{"borderRadius":{"values":{},"unit":"px","locked":true}},"blockWidth":{"customWidth":{"value":[],"unit":["px","px","px","px"]},"customHeight":{"value":[],"unit":["px","px","px","px"]}},"shadow":{},"panelShadow":{},"typography":{},"typographyCook":{},"animation":{"duration":700,"easing":"ease","type":""},"responsive":{},"position":{"positionType":["","","",""],"positions":{"values":{}}},"csstransform":{},"iconBox_icon":{"icon":{"font":"rhicon rhi-paper-plane","svg":"","image":""},"fill":"#2184f9","fillhover":"#2184f9","type":"font"},"typographyLabel":{}} -->
    <div id="gspb_button-id-gsbp-f5b4d4e6-b10d" class="gspb_button_wrapper gspb_button-id-gsbp-f5b4d4e6-b10d wp-block-greenshift-blocks-button"><a class="gspb-buttonbox" rel="noopener"><span class="gspb-buttonbox-textwrap"><span class="gspb-buttonbox-text"><span class="gspb-buttonbox-title">Schedule A Demo</span></span></span></a></div>
    <!-- /wp:greenshift-blocks/button --></div>
    <!-- /wp:greenshift-blocks/row-column --> </div></div>
    <!-- /wp:greenshift-blocks/row --></div>
    <!-- /wp:greenshift-blocks/container -->',
);
